
POST http://localhost:4000/products HTTP/1.1
Content-Type: application/json

  [
  {
    "category": 1,
    "subcategory": 2,
    "productName": "Public charge 1",
    "manufacturer": "Solar Power Inc.",
    "country": "China",
    "price": 199,
    "description": "High-efficiency solar panel for residential and commercial use.",
    "img": "../images/products/public-charging.png",
    "discount": 0
  },
  {
    "category": 1,
    "subcategory": 2,
    "productName": "Public charge 2",
    "manufacturer": "Sunergy",
    "country": "USA",
    "price": 350,
    "description": "Premium solar panel with advanced photovoltaic technology.",
    "img": "../images/products/public-charging.png",
    "discount": 0.20
  },
  {

    "category": 1,
    "subcategory": 2,
    "productName": "Public charge 3",
    "manufacturer": "GreenEco",
    "country": "Germany",
    "price": 400,
    "description": "Eco-friendly solar panel for sustainable energy production.",
    "img": "../images/products/public-charging.png",
    "discount": 0.10
  },
  {
    "category": 1,
    "subcategory": 2,
    "productName": "Public charge 4",
    "manufacturer": "Solar Power Inc.",
    "country": "China",
    "price": 299,
    "description": "High-efficiency solar panel for residential and commercial use.",
    "img": "../images/products/public-charging.png",
    "discount": 0.15
  },
  {
    "category": 1,
    "subcategory": 2,
    "productName": "Public charge 5",
    "manufacturer": "Sunergy",
    "country": "USA",
    "price": 130,
    "description": "Premium solar panel with advanced photovoltaic technology.",
    "img": "../images/products/public-charging.png",
    "discount": 0.25
  },
  {
    "category": 1,
    "subcategory": 2,
    "productName": "Public charge 6",
    "manufacturer": "GreenEco",
    "country": "Germany",
    "price": 400,
    "description": "Eco-friendly solar panel for sustainable energy production.",
    "img": "../images/products/public-charging.png",
    "discount": 0
  },
  {
    "category": 1,
    "subcategory": 3,
    "productName": "Super charging 7",
    "manufacturer": "Solar Power Inc.",
    "country": "China",
    "price": 290,
    "description": "High-efficiency solar panel for residential and commercial use.",
    "img": "../images/products/super-charge.jpg",
    "discount": 0
  },
  {
    "category": 1,
    "subcategory": 3,
    "productName": "Super charging 8",
    "manufacturer": "Sunergy",
    "country": "USA",
    "price": 3500,
    "description": "Premium solar panel with advanced photovoltaic technology.",
    "img": "../images/products/super-charge.jpg",
    "discount": 0.20
  },
  {
    "category": 1,
    "subcategory": 3,
    "productName": "Super charging 9",
    "manufacturer": "GreenEco",
    "country": "Germany",
    "price": 4000,
    "description": "Eco-friendly solar panel for sustainable energy production.",
    "img": "../images/products/super-charge.jpg",
    "discount": 0.15
  },
  {
    "category": 1,
    "subcategory": 3,
    "productName": "Super charging 10",
    "manufacturer": "Solar Power Inc.",
    "country": "China",
    "price": 2990,
    "description": "High-efficiency solar panel for residential and commercial use.",
    "img": "../images/products/super-charge.jpg",
    "discount": 0.1
  },
  {
    "category": 1,
    "subcategory": 3,
    "productName": "Super charging 11",
    "manufacturer": "Sunergy",
    "country": "USA",
    "price": 3500,
    "description": "Premium solar panel with advanced photovoltaic technology.",
    "img": "../images/products/super-charge.jpg",
    "discount": 0
  }
  ]