import img from "../images/products/Charger.jpeg";
import img1 from "../images/products/solar-panel-1.jpeg";



const product = [
    {
    id: 1,
    category: 1,
    subcategory: 1,
    productName: 'Charger 1',
    manufacturer: 'Tesla',
    country: 'China',
    price: 200,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0,
},
{
    id: 2,
    category: 1,
    subcategory: 1,
    productName: 'Charger 2',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 200,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.30,
},
{
    id: 3,
    category: 1,
    subcategory: 1,
    productName: 'Charger 3',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 300,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0,
},
{
    id: 4,
    category: 1,
    subcategory: 1,
    productName: 'Charger 4',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 5,
    category: 1,
    subcategory: 1,
    productName: 'Charger 5',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0,
},
{
    id: 6,
    category: 1,
    subcategory: 1,
    productName: 'Charger 6',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 7,
    category: 1,
    subcategory: 1,
    productName: 'Charger 7',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0,
},
{
    id: 11,
    category: 1,
    subcategory: 1,
    productName: 'Charger 8',
    manufacturer: 'Tesla',
    country: 'China',
    price: 200,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.50,
},
{
    id: 12,
    category: 1,
    subcategory: 1,
    productName: 'Charger 9',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 200,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.30,
},
{
    id: 13,
    category: 1,
    subcategory: 1,
    productName: 'Charger 10',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 300,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.40,
},
{
    id: 14,
    category: 1,
    subcategory: 1,
    productName: 'Charger 11',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 15,
    category: 1,
    subcategory: 1,
    productName: 'Charger 12',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 16,
    category: 1,
    subcategory: 1,
    productName: 'Charger 13',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 17,
    category: 1,
    subcategory: 1,
    productName: 'Charger 14',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 18,
    category: 1,
    subcategory: 1,
    productName: 'Charger 15',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0,
},
{
    id: 19,
    category: 1,
    subcategory: 1,
    productName: 'Charger 16',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0,
},
{
    id: 20,
    category: 1,
    subcategory: 1,
    productName: 'Charger 17',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: 'Canadian Solar Panel HiKu6 Mono PERC 530 W ~ 555 W CS6W-530',
    img: img,
    discount: 0,
},
{
    id: 21,
    category: 2,
    subcategory: 1,
    productName: 'Solar panel 1',
    manufacturer: 'Akura',
    country: 'Japan',
    price: 133,
    description: 'Canadian Solar Panel HiKu6 Mono PERC 530 W ~ 555 W CS6W-530',
    img: img1,
    discount: 0.3,
},
{
    id: 22,
    category: 2,
    subcategory: 1,
    productName: 'Solar panel 2',
    manufacturer: 'Akura',
    country: 'Japan',
    price: 133,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img1,
    discount: 0,
},
{
    id: 23,
    category: 2,
    subcategory: 1,
    productName: 'Solar panel 3',
    manufacturer: 'Akura',
    country: 'Japan',
    price: 133,
    description: 'Canadian Solar Panel HiKu6 Mono PERC 530 W ~ 555 W CS6W-530',
    img: img1,
    discount: 0,
},
{
    id: 24,
    category: 2,
    subcategory: 1,
    productName: 'Solar panel 4',
    manufacturer: 'Akura',
    country: 'Japan',
    price: 133,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img1,
    discount: 0.5,
},
{
    id: 25,
    category: 2,
    subcategory: 1,
    productName: 'Solar panel 5',
    manufacturer: 'Akura',
    country: 'Japan',
    price: 133,
    description: 'Canadian Solar Panel HiKu6 Mono PERC 530 W ~ 555 W CS6W-530',
    img: img1,
    discount: 0,
},
{
    id: 26,
    category: 2,
    subcategory: 1,
    productName: 'Solar panel 6',
    manufacturer: 'Akura',
    country: 'Japan',
    price: 133,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img1,
    discount: 0,
},
{
    id: 27,
    category: 2,
    subcategory: 1,
    productName: 'Solar panel 7',
    manufacturer: 'Akura',
    country: 'Japan',
    price: 133,
    description: 'Canadian Solar Panel HiKu6 Mono PERC 530 W ~ 555 W CS6W-530',
    img: img1,
    discount: 0,
},
{
    id: 28,
    category: 2,
    subcategory: 1,
    productName: 'Solar panel 8',
    manufacturer: 'Akura',
    country: 'Japan',
    price: 133,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img1,
    discount: 0,
},
];

export default product;
