import img from "../images/products/Charger.jpeg";
import img1 from "../images/products/solar-panel-1.jpeg";
import img2 from "../images/products/home-battery-pack.jpeg";
import img3 from "../images/products/energy-efficient-products.jpg";
import img4 from "../images/products/wind-turbine.jpg";
import img5 from "../images/products/inverter.jpg";



const product = [
    {
    id: 1,
    category: 1,
    subcategory: 1,
    productName: 'Charger 1',
    manufacturer: 'Tesla',
    country: 'China',
    price: 200,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0,
},
{
    id: 2,
    category: 1,
    subcategory: 1,
    productName: 'Charger 2',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 200,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.30,
},
{
    id: 3,
    category: 1,
    subcategory: 1,
    productName: 'Charger 3',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 300,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0,
},
{
    id: 4,
    category: 1,
    subcategory: 1,
    productName: 'Charger 4',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 5,
    category: 1,
    subcategory: 1,
    productName: 'Charger 5',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0,
},
{
    id: 6,
    category: 1,
    subcategory: 1,
    productName: 'Charger 6',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 7,
    category: 1,
    subcategory: 1,
    productName: 'Charger 7',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0,
},
{
    id: 11,
    category: 1,
    subcategory: 1,
    productName: 'Charger 8',
    manufacturer: 'Tesla',
    country: 'China',
    price: 200,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.50,
},
{
    id: 12,
    category: 1,
    subcategory: 1,
    productName: 'Charger 9',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 200,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.30,
},
{
    id: 13,
    category: 1,
    subcategory: 1,
    productName: 'Charger 10',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 300,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.40,
},
{
    id: 14,
    category: 1,
    subcategory: 1,
    productName: 'Charger 11',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 15,
    category: 1,
    subcategory: 1,
    productName: 'Charger 12',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 16,
    category: 1,
    subcategory: 1,
    productName: 'Charger 13',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 17,
    category: 1,
    subcategory: 1,
    productName: 'Charger 14',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 18,
    category: 1,
    subcategory: 1,
    productName: 'Charger 15',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0,
},
{
    id: 19,
    category: 1,
    subcategory: 1,
    productName: 'Charger 16',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0,
},
{
    id: 20,
    category: 1,
    subcategory: 1,
    productName: 'Charger 17',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: 'Canadian Solar Panel HiKu6 Mono PERC 530 W ~ 555 W CS6W-530',
    img: img,
    discount: 0,
},
{
    id: 21,
    category: 2,
    subcategory: 1,
    productName: 'Solar panel 1',
    manufacturer: 'Akura',
    country: 'Japan',
    price: 133,
    description: 'Canadian Solar Panel HiKu6 Mono PERC 530 W ~ 555 W CS6W-530',
    img: img1,
    discount: 0.3,
},
{
    id: 22,
    category: 2,
    subcategory: 1,
    productName: 'Solar panel 2',
    manufacturer: 'Akura',
    country: 'Japan',
    price: 133,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img1,
    discount: 0,
},
{
    id: 23,
    category: 2,
    subcategory: 1,
    productName: 'Solar panel 3',
    manufacturer: 'Akura',
    country: 'Japan',
    price: 133,
    description: 'Canadian Solar Panel HiKu6 Mono PERC 530 W ~ 555 W CS6W-530',
    img: img1,
    discount: 0,
},
{
    id: 24,
    category: 2,
    subcategory: 1,
    productName: 'Solar panel 4',
    manufacturer: 'Akura',
    country: 'Japan',
    price: 133,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img1,
    discount: 0.5,
},
{
    id: 25,
    category: 2,
    subcategory: 1,
    productName: 'Solar panel 5',
    manufacturer: 'Akura',
    country: 'Japan',
    price: 133,
    description: 'Canadian Solar Panel HiKu6 Mono PERC 530 W ~ 555 W CS6W-530',
    img: img1,
    discount: 0,
},
{
    id: 26,
    category: 2,
    subcategory: 1,
    productName: 'Solar panel 6',
    manufacturer: 'Akura',
    country: 'Japan',
    price: 133,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img1,
    discount: 0,
},
{
    id: 27,
    category: 2,
    subcategory: 1,
    productName: 'Solar panel 7',
    manufacturer: 'Akura',
    country: 'Japan',
    price: 133,
    description: 'Canadian Solar Panel HiKu6 Mono PERC 530 W ~ 555 W CS6W-530',
    img: img1,
    discount: 0,
},
{
    id: 28,
    category: 2,
    subcategory: 1,
    productName: 'Solar panel 8',
    manufacturer: 'Akura',
    country: 'Japan',
    price: 133,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img1,
    discount: 0,
},
{
    id: 29,
    category: 3,
    subcategory: 1,
    productName: 'Battery pack 1',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 133,
    description: 'Powerporter 11.0 Energy Capacity: 11.6kWh',
    img: img2,
    discount: 0.3,
},
{
    id: 30,
    category: 3,
    subcategory: 1,
    productName: 'Battery pack 2',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 233,
    description: 'Powerporter 11.0 Energy Capacity: 13.6kWh',
    img: img2,
    discount: 0,
},
{
    id: 31,
    category: 3,
    subcategory: 1,
    productName: 'Battery pack 3',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 533,
    description: 'Powerporter 11.0 Energy Capacity: 14.6kWh',
    img: img2,
    discount: 0,
},
{
    id: 32,
    category: 3,
    subcategory: 1,
    productName: 'Battery pack 4',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 433,
    description: 'Powerporter 11.0 Energy Capacity: 16.6kWh',
    img: img2,
    discount: 0.5,
},
{
    id: 33,
    category: 3,
    subcategory: 1,
    productName: 'Battery pack 5',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 733,
    description: 'Powerporter 11.0 Energy Capacity: 20.6kWh',
    img: img2,
    discount: 0.1,
},
{
    id: 34,
    category: 3,
    subcategory: 1,
    productName: 'Battery pack 6',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 733,
    description: 'Powerporter 11.0 Energy Capacity: 19.6kWh',
    img: img2,
    discount: 0,
},
{
    id: 35,
    category: 3,
    subcategory: 1,
    productName: 'Battery pack 7',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 533,
    description: 'Powerporter 11.0 Energy Capacity: 19.6kWh',
    img: img2,
    discount: 0,
},
{
    id: 36,
    category: 3,
    subcategory: 1,
    productName: 'Battery pack 8',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 1033,
    description: 'Powerporter 11.0 Energy Capacity: 22.6kWh',
    img: img2,
    discount: 0,
},
{
    id: 37,
    category: 4,
    subcategory: 1,
    productName: 'Energy-efficient appliance 1',
    manufacturer: 'EcoTech',
    country: 'Germany',
    price: 899,
    description: 'Energy-efficient appliance suitable for refrigeration needs. EcoTech presents the Energy Storage Unit 2000 with a capacity of 23.5 kWh, ideal for powering eco-friendly refrigerators.',
    img: img3,
    discount: 0,
  },
  {
    id: 38,
    category: 4,
    subcategory: 1,
    productName: 'Energy-efficient appliance 2',
    manufacturer: 'GreenEnergy',
    country: 'Sweden',
    price: 1299,
    description: 'Upgrade your entertainment setup with this energy-efficient appliance. The PowerCell XR-500, manufactured by GreenEnergy, offers high-capacity energy storage of 25.8 kWh, perfect for powering modern televisions.',
    img: img3,
    discount: 0,
  },
  {
    id: 39,
    category: 4,
    subcategory: 1,
    productName: 'Energy-efficient appliance 3',
    manufacturer: 'SustainableTech',
    country: 'United States',
    price: 1499,
    description: 'SustainableTech introduces the EcoPower Pro 3000, an energy-efficient appliance designed for household needs. With a storage capacity of 28.4 kWh, it is suitable for powering energy-efficient refrigerators.',
    img: img3,
    discount: 0,
  },
  {
    id: 40,
    category: 4,
    subcategory: 1,
    productName: 'Energy-efficient appliance 4',
    manufacturer: 'RenewableCo',
    country: 'Canada',
    price: 1099,
    description: 'RenewableCo presents the RenewaCharge XE-1200, an energy-efficient solution for powering appliances like pumps. With a storage capacity of 26.5 kWh, it ensures reliable and eco-friendly pump operation.',
    img: img3,
    discount: 0,
  },
  {
    id: 41,
    category: 4,
    subcategory: 1,
    productName: 'Energy-efficient appliance 5',
    manufacturer: 'EcoInnovate',
    country: 'Australia',
    price: 1699,
    description: 'Upgrade to the GreenPower Ultra 4000, an energy-efficient appliance designed for sustainable living. With a capacity of 30.2 kWh, it is suitable for powering energy-efficient refrigerators and other household appliances.',
    img: img3,
    discount: 0,
  },
  {
    id: 42,
    category: 5,
    subcategory: 1,
    productName: 'Wind turnbine 1',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 133,
    description: 'Powerporter 11.0 Energy Capacity: 11.6kWh',
    img: img4,
    discount: 0.3,
},
{
    id: 43,
    category: 5,
    subcategory: 1,
    productName: 'Wind turnbine 2',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 233,
    description: 'Powerporter 11.0 Energy Capacity: 13.6kWh',
    img: img4,
    discount: 0,
},
{
    id: 44,
    category: 5,
    subcategory: 1,
    productName: 'Wind turnbine 3',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 533,
    description: 'Powerporter 11.0 Energy Capacity: 14.6kWh',
    img: img4,
    discount: 0,
},
{
    id: 45,
    category: 5,
    subcategory: 1,
    productName: 'Wind turnbine 4',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 433,
    description: 'Powerporter 11.0 Energy Capacity: 16.6kWh',
    img: img4,
    discount: 0.5,
},
{
    id: 46,
    category: 5,
    subcategory: 1,
    productName: 'Wind turnbine 5',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 733,
    description: 'Powerporter 11.0 Energy Capacity: 20.6kWh',
    img: img4,
    discount: 0.1,
},
{
    id: 47,
    category: 5,
    subcategory: 1,
    productName: 'Wind turnbine 6',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 733,
    description: 'Powerporter 11.0 Energy Capacity: 19.6kWh',
    img: img4,
    discount: 0,
},
{
    id: 48,
    category: 5,
    subcategory: 1,
    productName: 'Wind turnbine 7',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 533,
    description: 'Powerporter 11.0 Energy Capacity: 19.6kWh',
    img: img4,
    discount: 0,
},
{
    id: 49,
    category: 5,
    subcategory: 1,
    productName: 'Wind turnbine 8',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 1033,
    description: 'Powerporter 11.0 Energy Capacity: 22.6kWh',
    img: img4,
    discount: 0,
},
{
    id: 50,
    category: 5,
    subcategory: 1,
    productName: 'Wind turnbine 9',
    manufacturer: 'EcoTech',
    country: 'Germany',
    price: 899,
    description: 'Energy-efficient appliance suitable for refrigeration needs. EcoTech presents the Energy Storage Unit 2000 with a capacity of 23.5 kWh, ideal for powering eco-friendly refrigerators.',
    img: img4,
    discount: 0,
  },
  {
    id: 51,
    category: 5,
    subcategory: 1,
    productName: 'Wind turnbine 10',
    manufacturer: 'GreenEnergy',
    country: 'Sweden',
    price: 1299,
    description: 'Upgrade your entertainment setup with this energy-efficient appliance. The PowerCell XR-500, manufactured by GreenEnergy, offers high-capacity energy storage of 25.8 kWh, perfect for powering modern televisions.',
    img: img4,
    discount: 0,
  },
  {
    id: 52,
    category: 5,
    subcategory: 1,
    productName: 'Wind turnbine 11',
    manufacturer: 'SustainableTech',
    country: 'United States',
    price: 1499,
    description: 'SustainableTech introduces the EcoPower Pro 3000, an energy-efficient appliance designed for household needs. With a storage capacity of 28.4 kWh, it is suitable for powering energy-efficient refrigerators.',
    img: img4,
    discount: 0,
  },
  {
    id: 53,
    category: 6,
    subcategory: 1,
    productName: 'Inverter 1',
    manufacturer: 'RenewableCo',
    country: 'Canada',
    price: 1099,
    description: 'RenewableCo presents the RenewaCharge XE-1200, an energy-efficient solution for powering appliances like pumps. With a storage capacity of 26.5 kWh, it ensures reliable and eco-friendly pump operation.',
    img: img5,
    discount: 0,
  },
  {
    id: 54,
    category: 6,
    subcategory: 1,
    productName: 'Inverter 2',
    manufacturer: 'EcoInnovate',
    country: 'Australia',
    price: 1699,
    description: 'Upgrade to the GreenPower Ultra 4000, an energy-efficient appliance designed for sustainable living. With a capacity of 30.2 kWh, it is suitable for powering energy-efficient refrigerators and other household appliances.',
    img: img5,
    discount: 0,
  },
  {
    id: 55,
    category: 6,
    subcategory: 1,
    productName: 'Inverter 3',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 133,
    description: 'Powerporter 11.0 Energy Capacity: 11.6kWh',
    img: img5,
    discount: 0.3,
},
{
    id: 56,
    category: 6,
    subcategory: 1,
    productName: 'Inverter 4',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 233,
    description: 'Powerporter 11.0 Energy Capacity: 13.6kWh',
    img: img5,
    discount: 0,
},
{
    id: 57,
    category: 6,
    subcategory: 1,
    productName: 'Inverter 5',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 533,
    description: 'Powerporter 11.0 Energy Capacity: 14.6kWh',
    img: img5,
    discount: 0,
},
{
    id: 58,
    category: 6,
    subcategory: 1,
    productName: 'Inverter 6',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 433,
    description: 'Powerporter 11.0 Energy Capacity: 16.6kWh',
    img: img5,
    discount: 0.5,
},
{
    id: 59,
    category: 6,
    subcategory: 1,
    productName: 'Inverter 7',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 733,
    description: 'Powerporter 11.0 Energy Capacity: 20.6kWh',
    img: img5,
    discount: 0.1,
},
{
    id: 60,
    category: 6,
    subcategory: 1,
    productName: 'Inverter 8',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 733,
    description: 'Powerporter 11.0 Energy Capacity: 19.6kWh',
    img: img5,
    discount: 0,
},
{
    id: 61,
    category: 6,
    subcategory: 1,
    productName: 'Inverter 9',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 533,
    description: 'Powerporter 11.0 Energy Capacity: 19.6kWh',
    img: img5,
    discount: 0,
},
{
    id: 62,
    category: 6,
    subcategory: 1,
    productName: 'Inverter 10',
    manufacturer: 'ABB',
    country: 'Finland',
    price: 1033,
    description: 'Powerporter 11.0 Energy Capacity: 22.6kWh',
    img: img5,
    discount: 0,
},
{
    id: 63,
    category: 6,
    subcategory: 1,
    productName: 'Inverter 11',
    manufacturer: 'EcoTech',
    country: 'Germany',
    price: 899,
    description: 'Energy-efficient appliance suitable for refrigeration needs. EcoTech presents the Energy Storage Unit 2000 with a capacity of 23.5 kWh, ideal for powering eco-friendly refrigerators.',
    img: img5,
    discount: 0,
  },
  {
    id: 64,
    category: 6,
    subcategory: 1,
    productName: 'Inverter 12',
    manufacturer: 'GreenEnergy',
    country: 'Sweden',
    price: 1299,
    description: 'Upgrade your entertainment setup with this energy-efficient appliance. The PowerCell XR-500, manufactured by GreenEnergy, offers high-capacity energy storage of 25.8 kWh, perfect for powering modern televisions.',
    img: img5,
    discount: 0,
  },
  {
    id: 65,
    category: 6,
    subcategory: 1,
    productName: 'Inverter 13',
    manufacturer: 'SustainableTech',
    country: 'United States',
    price: 1499,
    description: 'SustainableTech introduces the EcoPower Pro 3000, an energy-efficient appliance designed for household needs. With a storage capacity of 28.4 kWh, it is suitable for powering energy-efficient refrigerators.',
    img: img5,
    discount: 0,
  },
  {
    id: 66,
    category: 6,
    subcategory: 1,
    productName: 'Inverter 14',
    manufacturer: 'RenewableCo',
    country: 'Canada',
    price: 1099,
    description: 'RenewableCo presents the RenewaCharge XE-1200, an energy-efficient solution for powering appliances like pumps. With a storage capacity of 26.5 kWh, it ensures reliable and eco-friendly pump operation.',
    img: img5,
    discount: 0,
  },
  {
    id: 67,
    category: 6,
    subcategory: 1,
    productName: 'Inverter 15',
    manufacturer: 'EcoInnovate',
    country: 'Australia',
    price: 1699,
    description: 'Upgrade to the GreenPower Ultra 4000, an energy-efficient appliance designed for sustainable living. With a capacity of 30.2 kWh, it is suitable for powering energy-efficient refrigerators and other household appliances.',
    img: img5,
    discount: 0,
  },
  
];

export default product;
