import img from "../images/products/Charger.jpeg";
const product = [
    {
    id: 1,
    productName: 'Charger 1',
    manufacturer: 'Tesla',
    country: 'China',
    price: 200,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.50,
},
{
    id: 2,
    productName: 'Charger 2',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 200,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.30,
},
{
    id: 3,
    productName: 'Charger 3',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 300,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.40,
},
{
    id: 4,
    productName: 'Charger 4',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 5,
    productName: 'Charger 5',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 6,
    productName: 'Charger 6',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 7,
    productName: 'Charger 7',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 11,
    productName: 'Charger 1',
    manufacturer: 'Tesla',
    country: 'China',
    price: 200,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.50,
},
{
    id: 12,
    productName: 'Charger 2',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 200,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.30,
},
{
    id: 13,
    productName: 'Charger 3',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 300,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.40,
},
{
    id: 14,
    productName: 'Charger 4',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 15,
    productName: 'Charger 5',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 16,
    productName: 'Charger 6',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
{
    id: 17,
    productName: 'Charger 7',
    manufacturer: 'Ching Chong',
    country: 'China',
    price: 400,
    description: '8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station',
    img: img,
    discount: 0.9,
},
];

export default product;
