export let allProducts = [
  {
    id: "1",
    productName: "Charger 1",
    category: 1,
    subcategory: 1,
    manufacturer: "Tesla",
    country: "China",
    description: "This is a test charger description.",
    cost: "99.99$",
    image: "Charger.jpeg",
    discount: 0,
    size: "6.5ft x 3.25ft",
    material: "Aluminum",
  },
  {
    id: "2",
    productName: "Charger 2",
    category: 1,
    subcategory: 1,
    manufacturer: "Tesla",
    country: "China",
    description: "This is a test charger description.",
    cost: "99.99$",
    image: "charger2.png",
    discount: 0,
    size: "6.5ft x 3.25ft",
    material: "Aluminum",
  },
  {
    id: "3",
    productName: "Charger 3",
    category: 1,
    subcategory: 1,
    manufacturer: "Tesla",
    country: "China",
    description: "This is a test charger description.",
    cost: "99.99$",
    image: "charger3.png",
    discount: 0,
    size: "6.5ft x 3.25ft",
    material: "Aluminum",
  },
  {
    id: "4",
    productName: "Charger 4",
    category: 1,
    subcategory: 1,
    manufacturer: "Tesla",
    country: "China",
    description: "This is a test charger description.",
    cost: "99.99$",
    image: "Charger.jpeg",
    discount: 0,
    size: "6.5ft x 3.25ft",
    material: "Aluminum",
  },
  {
    id: "21",
    productName: "Solar Panel 1",
    category: 2,
    subcategory: 1,
    manufacturer: "Tesla",
    country: "China",
    description: "This is a test solar panel description.",
    cost: "99.99$",
    image: "polycrystalline_solar_panel.png",
    size: "6.5ft x 3.25ft",
    material: "Polycrystalline",
    discount: 0,
  },
  {
    id: "22",
    productName: "Solar Panel 2",
    category: 2,
    subcategory: 1,
    manufacturer: "Tesla",
    country: "China",
    description: "This is a test solar panel description.",
    cost: "99.99$",
    image: "monochrystalline_solar_panels.png",
    size: "6.5ft x 3.25ft",
    material: "monochrystalline",
    discount: 0,
  },
  {
    id: "23",
    category: 2,
    subcategory: 1,
    productName: "Solar Panel 3",
    manufacturer: "Tesla",
    country: "China",
    description: "This is a test solar panel description.",
    price: 99.99,
    image: "thin_film_solar_cells_.png",
    size: "6.5ft x 3.25ft",
    material: "monochrystalline",
    discount: 0,
  },
  {
    id: "24",
    category: 2,
    subcategory: 1,
    productName: "Solar panel 4",
    manufacturer: "Tesla",
    country: "China",
    price: 200,
    description:
      "8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station",
    image: "mono.jpg",
    discount: 0,
  },
];
